### PR TITLE
docs(README): add 64-bit RISC-V QEMU instructions

### PR DESCRIPTION
**Pull request by mkroening**
Related: https://github.com/hermit-os/hermit-rs-template/issues/65

### CODE REVIEW

**Comment by marcomaas1990** [comment]
I'm getting errors with the virtio devices when compiling for the risc-v hermit target.

**Comment by mkroening** [comment]
> I'm getting errors with the virtio devices when compiling the hermit-rs-template for the risc-v hermit target.

Yeah, virtio support on RISC-V is not quite there yet. I have opened https://github.com/hermit-os/kernel/issues/1217 to track that.

Are you happy with these instructions for running without virtio, though?

**Comment by marcomaas1990** [comment]
I will check the running in qemu part later, but what should I change for successfuly compiling when `cargo build --target riscv64gc-unknown-hermit` isn't working properly? I'm not quite sure.

**Comment by mkroening** [comment]
> I will check the running in qemu part later, but what should I change for successfuly compiling when `cargo build --target riscv64gc-unknown-hermit` isn't working properly? I'm not quite sure.

Disabling all default features of the `hermit` dependency should work.

**Comment by marcomaas1990** [comment]
Can you help me changing the Cargo.toml?
I tried adding
`[target.'cfg(target_arch = "riscv64")'.dependencies]
risv = {version = "0.11", default-features = false}`
to the config file, but I keep getting errors.

**Comment by marcomaas1990** [comment]
> > I'm getting errors with the virtio devices when compiling the hermit-rs-template for the risc-v hermit target.
> 
> Yeah, virtio support on RISC-V is not quite there yet. I have opened [hermit-os/kernel#1217](https://github.com/hermit-os/kernel/issues/1217) to track that.
> 
> Are you happy with these instructions for running without virtio, though?

Yeah, they are working now.

**Pull request merged**
